
project_id = "iesugielppyhhvtdzsqq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[realtime]
enabled = true
port = 54327

[edge_functions]
[edge_functions.get-key-containers]
verify_jwt = false

[edge_functions.create-get-key-containers-function]
verify_jwt = false
