// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iesugielppyhhvtdzsqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imllc3VnaWVscHB5aGh2dGR6c3FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4ODAyMDUsImV4cCI6MjA2MTQ1NjIwNX0.QQYxM6pz6h9IGWYGxysvW8p1KFmHk3O_RdqnpwJYE8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);